version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      non-major:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "monthly"
