// Auto-generated by scripts/split-zotero-namespaces.mjs
// Zotero global namespace bindings extracted from date.d.ts

/// <reference path="./date.d.ts" />

declare namespace Zotero {
  const Date: _ZoteroTypes.Utilities_Date;
}
