// Auto-generated by scripts/split-zotero-namespaces.mjs
// Zotero global namespace bindings extracted from utilities.d.ts

/// <reference path="./utilities.d.ts" />

declare namespace Zotero {
  const Utilities: _ZoteroTypes.Utilities;
}
