// Auto-generated by scripts/split-zotero-namespaces.mjs
// Zotero global namespace bindings extracted from itemPaneManager.d.ts

/// <reference path="./itemPaneManager.d.ts" />

declare namespace Zotero {
  const ItemPaneManager: _ZoteroTypes.ItemPaneManager;
}
