// Auto-generated by scripts/split-zotero-namespaces.mjs
// Zotero global namespace bindings extracted from itemTreeManager.d.ts

/// <reference path="./itemTreeManager.d.ts" />

declare namespace Zotero {
  const ItemTreeManager: _ZoteroTypes.ItemTreeManager;
}
