// Auto-generated by scripts/split-zotero-namespaces.mjs
// Zotero global namespace bindings extracted from menuManager.d.ts

/// <reference path="./menuManager.d.ts" />

declare namespace Zotero {
  const MenuManager: _ZoteroTypes.MenuManager;
}
