// Auto-generated by scripts/split-zotero-namespaces.mjs
// Zotero global namespace bindings extracted from windowResourceManager.d.ts

/// <reference path="./windowResourceManager.d.ts" />

declare namespace Zotero {
  const WindowResourceManager: _ZoteroTypes.WindowResourceManager;
}
