// Auto-generated by scripts/split-zotero-namespaces.mjs
// Zotero global namespace bindings extracted from annotations.d.ts

/// <reference path="./annotations.d.ts" />

declare namespace Zotero {
  const Annotations: _ZoteroTypes.Annotations;
}
