// Auto-generated by scripts/split-zotero-namespaces.mjs
// Zotero global namespace bindings extracted from attachments.d.ts

/// <reference path="./attachments.d.ts" />

declare namespace Zotero {
  const Attachments: _ZoteroTypes.Attachments;
}
