// Auto-generated by scripts/split-zotero-namespaces.mjs
// Zotero global namespace bindings extracted from dataDirectory.d.ts

/// <reference path="./dataDirectory.d.ts" />

declare namespace Zotero {
  namespace DataDirectory {
    let dir: string;
  }
}
