// Auto-generated by scripts/split-zotero-namespaces.mjs
// Zotero global namespace bindings extracted from db.d.ts

/// <reference path="./db.d.ts" />

declare namespace Zotero {
  const DB: _ZoteroTypes.DB;
  const DBConnection: _ZoteroTypes.DBConnection;
}
