// Auto-generated by scripts/split-zotero-namespaces.mjs
// Zotero global namespace bindings extracted from fileHandlers.d.ts

/// <reference path="./fileHandlers.d.ts" />

declare namespace Zotero {
  const FileHandlers: _ZoteroTypes.FileHandlers;

  namespace OpenPDF {
    /**
     * @deprecated - use Zotero.FileHandlers.open
     */
    function openToPage(
      item: Zotero.Item,
      page: number,
      annotationKey?: string,
    ): Promise<void>;
  }
}
