// Auto-generated by scripts/split-zotero-namespaces.mjs
// Zotero global namespace bindings extracted from file.d.ts

/// <reference path="./file.d.ts" />

declare namespace Zotero {
  const File: _ZoteroTypes.File;
}
