// Auto-generated by scripts/split-zotero-namespaces.mjs
// Zotero global namespace bindings extracted from fulltext.d.ts

/// <reference path="./fulltext.d.ts" />

declare namespace Zotero {
  const Fulltext: _ZoteroTypes.FullText;
  const FullText: _ZoteroTypes.FullText;
}
