// Auto-generated by scripts/split-zotero-namespaces.mjs
// Zotero global namespace bindings extracted from http.d.ts

/// <reference path="./http.d.ts" />

declare namespace Zotero {
  const HTTP: _ZoteroTypes.HTTP;
}
