// Auto-generated by scripts/split-zotero-namespaces.mjs
// Zotero global namespace bindings extracted from notifier.d.ts

/// <reference path="./notifier.d.ts" />

declare namespace Zotero {
  const Notifier: _ZoteroTypes.Notifier;
}
