// Auto-generated by scripts/split-zotero-namespaces.mjs
// Zotero global namespace bindings extracted from plugins.d.ts

/// <reference path="./plugins.d.ts" />

declare namespace Zotero {
  const Plugins: _ZoteroTypes.Plugins;
}
