// Auto-generated by scripts/split-zotero-namespaces.mjs
// Zotero global namespace bindings extracted from preferencePanes.d.ts

/// <reference path="./preferencePanes.d.ts" />

declare namespace Zotero {
  const PreferencePanes: _ZoteroTypes.PreferencePanes;
}
