// Auto-generated by scripts/split-zotero-namespaces.mjs
// Zotero global namespace bindings extracted from progressWindow.d.ts

/// <reference path="./progressWindow.d.ts" />

declare namespace Zotero {
  class ProgressWindow {
    constructor(options?: { window?: Window; closeOnClick?: boolean });

    /**
     * Shows the progress window
     */
    show(): boolean;

    /**
     * Changes the "headline" shown at the top of the progress window
     */
    changeHeadline(text: string, icon?: string, postText?: string): void;

    /**
     * Adds a line to the progress window with the specified icon
     */
    addLines(
      labels: string | { [key: string | number | symbol]: string },
      icons: string | { [key: string | number | symbol]: string },
    ): void;

    /**
     * Add a description to the progress window
     *
     * <a> elements are turned into XUL links
     */
    addDescription(text: string): void;

    /**
     * Sets a timer to close the progress window. If a previous close timer was set,
     * clears it.
     * @param {Integer} ms The number of milliseconds to wait before closing the progress
     *     window.
     * @param {Boolean} [requireMouseOver] If true, wait until the mouse has touched the
     *     window before closing.
     */
    startCloseTimer(ms: number, requireMouseOver?: boolean): void;

    /**
     * Immediately closes the progress window if it is open.
     */
    close(): void;

    ItemProgress: _ZoteroTypes.ItemProgress;
  }

  const ProgressWindowSet: {
    closeAll(): void;
  };
}
