// Auto-generated by scripts/split-zotero-namespaces.mjs
// Zotero global namespace bindings extracted from reader.d.ts

/// <reference path="./reader.d.ts" />

declare namespace Zotero {
  const Reader: _ZoteroTypes.Reader;
}
