// Auto-generated by scripts/split-zotero-namespaces.mjs
// Zotero global namespace bindings extracted from server.d.ts

/// <reference path="./server.d.ts" />

declare namespace Zotero {
  const Server: _ZoteroTypes.Server;
}
