// Auto-generated by scripts/split-zotero-namespaces.mjs
// Zotero global namespace bindings extracted from session.d.ts

/// <reference path="./session.d.ts" />

declare namespace Zotero {
  namespace Session {
    const state: Record<string, any>;

    function init(): Promise<void>;
    function save(): Promise<void>;
    function debounceSave(): Promise<void>;
    function setLastClosedZoteroPaneState(): void;
  }
}
