// Auto-generated by scripts/split-zotero-namespaces.mjs
// Zotero global namespace bindings extracted from uiProperties.d.ts

/// <reference path="./uiProperties.d.ts" />

declare namespace Zotero {
  namespace UIProperties {
    function registerRoot(root: Element): void;
    function setAll(): void;
    function set(root: Element): void;
  }
}
