// Auto-generated by scripts/split-zotero-namespaces.mjs
// Zotero global namespace bindings extracted from uri.d.ts

/// <reference path="./uri.d.ts" />

declare namespace Zotero {
  const URI: _ZoteroTypes.URI;
}
