// Auto-generated by scripts/split-zotero-namespaces.mjs
// Zotero global namespace bindings extracted from users.d.ts

/// <reference path="./users.d.ts" />

declare namespace Zotero {
  const Users: _ZoteroTypes.Users;
}
