// Auto-generated by scripts/split-zotero-namespaces.mjs
// Zotero global namespace bindings extracted from promise.d.ts

/// <reference path="./promise.d.ts" />

declare namespace Zotero {
  /**
   * @deprecated Use standard Promise instead.
   */
  const Promise: _ZoteroTypes.Promise.Promise &
    _ZoteroTypes.Promise.PromiseConstructor<() => void>;
}
