// Auto-generated by scripts/split-zotero-namespaces.mjs
// Zotero global namespace bindings extracted from cachedTypes.d.ts

/// <reference path="./cachedTypes.d.ts" />

declare namespace Zotero {
  /*
   * Base function for retrieving ids and names of static types stored in the DB
   * (e.g. creatorType, fileType, charset, itemType)
   *
   * Extend using the following code within a child constructor:
   *
   * 	Zotero.CachedTypes.apply(this, arguments);
   *  this.constructor.prototype = new Zotero.CachedTypes();
   *
   * And the following properties:
   *
   *	this._typeDesc = '';
   *	this._typeDescPlural = '';
   *	this._idCol = '';
   *	this._nameCol = '';
   *	this._table = '';
   *
   * Optional properties:
   *
   *  this._allowAdd: Allow new types to be added via .add(name)
   *	this._ignoreCase: Ignore case when looking for types, and add new types as lowercase
   *
   * And add .init() to zotero.js
   */
  interface CachedTypes {
    new (): this;
    _types: { [idOrName: string]: _ZoteroTypes.CachedTypes.Type };
    _typesArray: _ZoteroTypes.CachedTypes.Type[];
    _typeDesc: string;
    _idCol: string;
    _nameCol: string;
    _table: string;
    _allowAdd: boolean;
    _ignoreCase: boolean;
    _hasCustom: boolean;

    /**
     * Add a new type to the data and return its id. If the type already exists, return its id.
     *
     * @param {String} name - Type name to add
     * @return {Integer|False} - The type id (new or existing), or false if invalid type name
     */
    add(name: string): Promise<number | false>;

    init(): Promise<void>;
    getName(idOrName: number | string): string;
    getID(idOrName: number | string): number | false;
    getAll(): _ZoteroTypes.CachedTypes.Type[];
    getTypes(): _ZoteroTypes.CachedTypes.Type[];
    isCustom(idOrName: number | string): boolean; // Currently used only for item types
    _getTypesFromDB(where: string, params?: object): Promise<unknown>;
    _cacheTypeData(type: _ZoteroTypes.CachedTypes.Type): void;
  }

  const CreatorTypes: _ZoteroTypes.CreatorTypes;
  const ItemTypes: _ZoteroTypes.ItemTypes;
  const FileTypes: _ZoteroTypes.FileTypes;
  const CharacterSets: _ZoteroTypes.CharacterSets;
  const RelationPredicates: _ZoteroTypes.RelationPredicates;
}
