// Auto-generated by scripts/split-zotero-namespaces.mjs
// Zotero global namespace bindings extracted from collections.d.ts

/// <reference path="./collections.d.ts" />

declare namespace Zotero {
  const Collections: _ZoteroTypes.Collections;
}
