// Auto-generated by scripts/split-zotero-namespaces.mjs
// Zotero global namespace bindings extracted from creators.d.ts

/// <reference path="./creators.d.ts" />

declare namespace Zotero {
  const Creators: _ZoteroTypes.Creators;
}
