// Auto-generated by scripts/split-zotero-namespaces.mjs
// Zotero global namespace bindings extracted from dataObjects.d.ts

/// <reference path="./dataObjects.d.ts" />

declare namespace Zotero {
  const DataObjects: _ZoteroTypes.DataObjects;
}
