// Auto-generated by scripts/split-zotero-namespaces.mjs
// Zotero global namespace bindings extracted from feeds.d.ts

/// <reference path="./feeds.d.ts" />

declare namespace Zotero {
  const Feeds: _ZoteroTypes.Feeds;
}
