// Auto-generated by scripts/split-zotero-namespaces.mjs
// Zotero global namespace bindings extracted from feedItem.d.ts

/// <reference path="./feedItem.d.ts" />

declare namespace Zotero {
  class FeedItem extends Zotero.Item {
    constructor(
      itemTypeOrID?: _ZoteroTypes.Item.ItemType | number,
      params?: object,
    );
  }
}
