// Auto-generated by scripts/split-zotero-namespaces.mjs
// Zotero global namespace bindings extracted from items.d.ts

/// <reference path="./items.d.ts" />

declare namespace Zotero {
  const Items: _ZoteroTypes.Items;
}
