// Auto-generated by scripts/split-zotero-namespaces.mjs
// Zotero global namespace bindings extracted from library.d.ts

/// <reference path="./library.d.ts" />

declare namespace Zotero {
  class Library extends _ZoteroTypes.Library.LibraryAbstract {
    _objectType: "library";
    _childObjectTypes: ["item", "collection", "search"];
    fixedLibraries: ["user"];
    libraryTypes: ["user"];
    libraryType: "user" | "group" | "feed";

    static readonly _dbColumns: [
      "type",
      "editable",
      "filesEditable",
      "version",
      "storageVersion",
      "lastSync",
      "archived",
    ];
  }
}
