// Auto-generated by scripts/split-zotero-namespaces.mjs
// Zotero global namespace bindings extracted from libraries.d.ts

/// <reference path="./libraries.d.ts" />

declare namespace Zotero {
  const Libraries: _ZoteroTypes.Libraries;
}
