// Auto-generated by scripts/split-zotero-namespaces.mjs
// Zotero global namespace bindings extracted from notes.d.ts

/// <reference path="./notes.d.ts" />

declare namespace Zotero {
  const Notes: _ZoteroTypes.Notes;
}
