// Auto-generated by scripts/split-zotero-namespaces.mjs
// Zotero global namespace bindings extracted from searches.d.ts

/// <reference path="./searches.d.ts" />

declare namespace Zotero {
  const Searches: _ZoteroTypes.Searches;
}
