// Auto-generated by scripts/split-zotero-namespaces.mjs
// Zotero global namespace bindings extracted from tags.d.ts

/// <reference path="./tags.d.ts" />

declare namespace Zotero {
  const Tags: _ZoteroTypes.Tags;
}
